### ISSUE TITLE
Sometimes wrong values are reported

### ISSUE THREAD

**Issue by BlackAlpha700** [pravussum/openhab2-addons#8] opened 2018-12-07 11:18 UTC
At first: I use a very short refreshInterval of 1 second! Maybe this is the only reason for the mentioned problems below...

Sometimes (very rare) the data reported from the air unit is wrong. For example the filter_life jumps from 78% to 0% and back to 78%. Maybe the air unit didn't answer fast enough and a timeout happened? Other values like fan speeds, temperatures and so on seem to be correct at this moment.

Yesterday another strange behavior happend:
For about 3 hours the room_temp reported was -327.7°C. (Maybe you say "switch the heating on", but did you ever enter a room at this temperature? ;-) )
I wasn't at home to check the air dial at this moment. The battery_life reported 0% and this maybe the reason the air unit didn't get any temperature information and the binding calculated this low temperature. A restart of the air unit (I'm able to switch the power from remote) and a openHAB restart didn't fix the problem. 3 hours later everything worked fine again and the battery_life reported is 12%.

Is it possible to skip the update of the affected channels if a problem like the above happens and report the collected values as a warning to the openHAB log instead?

I use openHAB 2.4.0_M5 and since today the alpha4 release of the binding. Before the update I've used alpha3.

**Comment by leaxidd** [comment] 2019-05-16 17:50
Hi Carsten,

-327,7 means in integer -32770, which Just seems to bei a rounded -32768 and this is -2^15 the Minimum value of a two Byte signed integer.

For the Filter Life it is also the Minimum value, but for unsigned one Byte integer.

So when the Binding reads the Minimum value, wenn probably should throw away that value or Just try to read it again. 

Fixing sich stuff ist hard, as you can't reproduce and Test this easily.

**Comment by BlackAlpha700** [comment] 2019-06-11 09:04
Hi @leaxidd ,

sorry for the late answer. I think a temperature ob -327,7°C is just impossible and you should throw the value away or try to read it again.

For the filter life it may be a possible solution to compare with the value read before. If it differs for more than 1 or 2% from the value before, throw the value away. My filter life is mostly about 6 months (180days) so the life should sink percent by percent and not 20% from one value to another.

The problem with the wrong temperature values appears mostly one or two times a day and if u use a persistence for drawing graphs e.g. in a sitemap such graphs were simply useless because of the wide range (-327°C to 25°C) on the y-axis.

**Comment by pravussum** [comment] 2019-10-14 09:03
I got the -327° bug as well, but for a couple of weeks now. I debugged it last week and the air unit indeed responds with all zero values, leading to the misinterpreted value for the room temperature. Beside the "room temperature" address there is another address in the google doc with the air unit addresses called "calculated room temperature" which seems to reliably report values. My assumption is, that the calculated temp is not taken from the air dial and consequently does not fail if the air dial batteries are down or the zwave connection is interrupted. I ended up changing the address of the room temp to the calculated one in my last commit. I have not prepeared a release since I wanted to look into the other issue regarding air unit restart. But you can just clone the repo and build the single binding via maven on the command line or I can upload the jar next week when I'm back from vacation.

**Comment by BlackAlpha700** [comment] 2019-11-16 10:20
Thanks for the update. I've tried the new version and the -327° bug with the room temperature is gone - but now I'm becoming no values any more and the room temperature shows 0°C permanently.

**Comment by pravussum** [comment] 2019-12-06 11:54
Fixed with d95836c

**Closed by pravussum** 2019-12-06 11:54 UTC
